name: tickets_og
description: "TicketsOG mobile Application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sizer: ^2.0.15
  http: ^1.4.0
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.7
  page_transition: ^2.1.0
#  flutter_localization: ^0.2.0
#  fluttertoast: ^8.2.5
  firebase_messaging: ^14.8.2
  connectivity_plus: ^6.0.3
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  bouncing_widget: ^2.0.0
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.0
  flutter_svg: ^2.0.10+1
  dropdown_button2: ^2.3.9
  iconsax: ^0.0.8
  dartz: ^0.10.1
  pin_code_fields: ^8.0.1
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.3.1
  mobile_scanner: ^6.0.6
  auto_size_text: ^3.0.0
  glass: ^2.0.0+2
  syncfusion_flutter_gauges: ^24.2.7
  jwt_decoder: ^2.0.1
  flutter_beep:
    git:
      url: https://github.com/trietho/flutter_beep.git
  tap_debouncer: ^2.2.0
  shimmer: ^3.0.0
  intl: ^0.19.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/png/
    - assets/images/svg/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
